# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSync < Formula
  desc "Git branch sync utility"
  homepage "https://github.com/jacobwgillespie/git-sync"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.0.0/git-sync_1.0.0_darwin_amd64.tar.gz"
      sha256 "df7fcc8a3b7f7d54096e996cc742550377c7b24eb44c1560155652c929db13f3"

      def install
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.0.0/git-sync_1.0.0_darwin_arm64.tar.gz"
      sha256 "61afa8f1a91a2f7f761ea6771ab5e9e340bb16878f5deb7d22c3fbc1ffd76449"

      def install
        bin.install "git-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.0.0/git-sync_1.0.0_linux_amd64.tar.gz"
      sha256 "5cbd2115951cc3125317ab3fe6e43e6ed2c27d7960e1972e27a0d13ad71dd668"

      def install
        bin.install "git-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.0.0/git-sync_1.0.0_linux_arm64.tar.gz"
      sha256 "95fcb49271abd318f47b21d0896f3dab006f6926d32912eb064bd41d502de86d"

      def install
        bin.install "git-sync"
      end
    end
  end
end
