# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSync < Formula
  desc "Git branch sync utility"
  homepage "https://github.com/jacobwgillespie/git-sync"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.1.0/git-sync_1.1.0_darwin_amd64.tar.gz"
      sha256 "56f6a81c512524815d8fbcf6a47531bb4283b5af85eb75e6734f4ab423ce3fce"

      def install
        bin.install "git-sync"
      end
    end
    on_arm do
      url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.1.0/git-sync_1.1.0_darwin_arm64.tar.gz"
      sha256 "d3391399214474aa7898ec310a114af67108c5c15afe7509a1fb47e6cf427197"

      def install
        bin.install "git-sync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.1.0/git-sync_1.1.0_linux_amd64.tar.gz"
        sha256 "e54d584b46ddccbdc90c08294dd856e08d25624ff094dc56cc7ce085aebbf9ed"

        def install
          bin.install "git-sync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jacobwgillespie/git-sync/releases/download/v1.1.0/git-sync_1.1.0_linux_arm64.tar.gz"
        sha256 "2533519761a2e25056ef3266722065e94658a700c7d12ebc4cf25e4162804ac9"

        def install
          bin.install "git-sync"
        end
      end
    end
  end
end
