# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KeyLight < Formula
  desc "CLI for Elgato Key Lights"
  homepage "https://github.com/jacobwgillespie/key-light"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.0/key-light_0.1.0_Darwin_arm64.tar.gz"
      sha256 "0d61e2de3db4bf0aad916d1f41ef54f905141fd174011b3e8632e70656ecae5f"

      def install
        bin.install "key-light"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.0/key-light_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "c3a52fedebc4e00052e386bd36be835e68b6eb256ec21a51d6a3d4d6c747a4fa"

      def install
        bin.install "key-light"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.0/key-light_0.1.0_Linux_arm64.tar.gz"
      sha256 "8067d7acf67ba7e4b43e7e703f8bb0f128cc19bb3162a849f95271290bedabd0"

      def install
        bin.install "key-light"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.0/key-light_0.1.0_Linux_x86_64.tar.gz"
      sha256 "fcbb0db1a127cab4979470ca22aae872072047ca9d2d7c62e9510272d83e1eb6"

      def install
        bin.install "key-light"
      end
    end
  end
end
