# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KeyLight < Formula
  desc "CLI for Elgato Key Lights"
  homepage "https://github.com/jacobwgillespie/key-light"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.1/key-light_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "1caa50ebd7a4adf5b29c7b7907a017893ffbcc4e30479b829f8e008448a4dc91"

      def install
        bin.install "key-light"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.1/key-light_0.1.1_Darwin_arm64.tar.gz"
      sha256 "db6a8caeb14fd124706ff8696cd0901f3e6c55d73a1010f2a83a9c598f4fa691"

      def install
        bin.install "key-light"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.1/key-light_0.1.1_Linux_arm64.tar.gz"
      sha256 "f2257a27818f24bf583c5fd36097719a70c200b124dfe9bd0aaa6c248c7b7217"

      def install
        bin.install "key-light"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/key-light/releases/download/v0.1.1/key-light_0.1.1_Linux_x86_64.tar.gz"
      sha256 "aeca3cb1511d8def998890abb8a3412b21e799570bc7a3007e092253b0b3590d"

      def install
        bin.install "key-light"
      end
    end
  end
end
