# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc "Run is a tool for running package.json scripts"
  homepage "https://github.com/jacobwgillespie/run"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.2.0/run_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "373048475882a47d0e351aac8e60ff37c0b7c888700b0dd7bb7a2bf4e784c7a5"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.2.0/run_0.2.0_Darwin_arm64.tar.gz"
      sha256 "9ca37b128f612d9ce25ae7832593857a6156aa1afe2693a67cf081954b787522"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.2.0/run_0.2.0_Linux_arm64.tar.gz"
      sha256 "6208ceb691708e35ba044b46b14952083512feded99a3c007a0c5848955f1727"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.2.0/run_0.2.0_Linux_x86_64.tar.gz"
      sha256 "eace9ccaa8708602d1f8b5293d7978475173fc356e652828abcfe6b273b58e18"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
  end

  test do
    system "#{bin}/run --help"
  end
end
