# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc "Run is a tool for running package.json scripts"
  homepage "https://github.com/jacobwgillespie/run"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.3.2/run_0.3.2_Darwin_arm64.tar.gz"
      sha256 "99ecf376e5074fc3d32dda5de350d7f03a58cd319ac6af4443a014ce2879d781"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.3.2/run_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "24845b335274e3196c8d3dc4569056e854d4d58940ab88596bf975dbd2ec4a9f"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.3.2/run_0.3.2_Linux_arm64.tar.gz"
      sha256 "513630870f7e81ca19b7071471b811d7ace472ba3705a6aa51e791e4b6ff284f"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobwgillespie/run/releases/download/v0.3.2/run_0.3.2_Linux_x86_64.tar.gz"
      sha256 "33fabf0a5dc033c76f3aa754468788686ab646a56e64190fed91db2a9b2fb7cc"

      def install
        bin.install "bin/run"
        bash_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "bash")
        fish_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "fish")
        zsh_comp = Utils.safe_popen_read("#{bin}/run", "--completion", "zsh")
        (bash_completion/"run").write bash_comp
        (fish_completion/"run.fish").write fish_comp
        (zsh_completion/"_run").write zsh_comp
      end
    end
  end

  test do
    system "#{bin}/run --help"
  end
end
