# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Terraform version wrapper"
  homepage "https://github.com/jacobwgillespie/tf"
  version "0.0.4"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.4/tf_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "5004a04da477090aa7aa03039687fa49fb04261f6a731c9c09b8a1939c63bb21"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.4/tf_0.0.4_Darwin_arm64.tar.gz"
    sha256 "fa7fde8fc5f5f6c6b8e6832acc8e42a17f768fc68dc75edb8167c1886a0885e2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.4/tf_0.0.4_Linux_x86_64.tar.gz"
    sha256 "7a532b2b141d219177d6059cd4482ce403810453def8cc79288c00e5f6ae1540"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.4/tf_0.0.4_Linux_arm64.tar.gz"
    sha256 "095844abe4739f08fe61f723610bfde606c596f9e67b1491353f2e00ebfc2a86"
  end

  def install
    bin.install "tf"
  end
end
