# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Terraform version wrapper"
  homepage "https://github.com/jacobwgillespie/tf"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.5/tf_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "794776640c767edd4c6580ab9bed383f4f48f16269203e805ea062b8ee9c279d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.5/tf_0.0.5_Darwin_arm64.tar.gz"
    sha256 "d7ef28fbf550d3165e37f337e6b3697b1579f9e69139aac63d2bc06d9688db2a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.5/tf_0.0.5_Linux_x86_64.tar.gz"
    sha256 "6335968c94eeb35091784c3755c86cfaad77b099832117649ea6c099553e0572"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jacobwgillespie/tf/releases/download/v0.0.5/tf_0.0.5_Linux_arm64.tar.gz"
    sha256 "4bb7adf5b6e231ddfb09537033dfb6d9da92d6a456fd39fd565ee64abf7fd6d4"
  end

  def install
    bin.install "tf"
  end
end
